[build.environment]
  PYTHON_VERSION = "3.12.7"

[build]
  base = "/streamlit"
  command = """\
    pip install -r requirements.txt && \
    mkdir googlenet_model && \
    wget https://github.com/Egi-putrA/googlenet-leukemia-classification/releases/download/v1.0.0/clahe_balanced_model.zip && \
    unzip clahe_balanced_model.zip -d googlenet_model && \
    rm clahe_balanced_model.zip
    """
[dev]
  command = "streamlit run main.py"
  port = 80
  targetPort = 8501
